# Generated by Django 3.2.7 on 2021-09-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creador',
            field=models.TextField(blank=True, null=True),
        ),
    ]
