# Generated by Django 3.2.7 on 2021-09-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_task_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creador',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
