# Generated by Django 3.2.7 on 2021-09-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_estatus_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='archivos',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
