# Generated by Django 3.2.7 on 2021-09-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_task_archivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='archivos',
            field=models.FileField(null=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
